name: lab
channels:
  - plotly
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - autopep8=1.4.4
  - colorlog=4.0.2
  - coverage=4.5.3
  - flaky=3.5.3
  - libgcc
  - numpy=1.16.3
  - openpyxl=2.6.1
  - pandas=0.24.2
  - pillow=6.2.0
  - pip=19.1.1
  - plotly=4.9.0
  - psutil=5.6.2
  - pycodestyle=2.5.0
  - pydash=4.2.1
  - pytest-cov=2.7.1
  - pytest-timeout=1.3.3
  - pytest=4.5.0
  - python=3.7.3
  - pytorch=1.3.1
  - pyyaml=5.1
  - regex=2019.05.25
  - scipy=1.3.0
  - ujson=1.35
  - xlrd=1.2.0
  - pip:
      - box2d-py==2.3.8
      - cloudpickle==0.5.2
      - colorlover==0.3.0
      - future==0.18.2
      - kaleido==0.2.1
      - opencv-python==4.1.0.25
      - pyopengl==3.1.0
      - ray==0.7.0
      - redis==2.10.6
      - tensorboard==2.1.1
      - xvfbwrapper==0.2.9
      - gym==0.12.1
      - gym[atari]
      - gym[box2d]
      - gym[classic_control]
      - pybullet==2.8.4
      - roboschool==1.0.46
      - atari-py==0.2.6
