name: lab
channels:
- pytorch
- conda-forge
- defaults
dependencies:
- autopep8=1.3.3=py_0
- blas=1.1=openblas
- colorlog=3.1.0=py36_0
- coverage=4.4.2=py36_0
- cython=0.27.3=py36_0
- flaky=3.4.0=py_0
- hdf5=1.10.1=1
- ipykernel=4.7.0=py36_0
- numpy=1.14.0=py36_blas_openblas_200
- openblas=0.2.20=7
- openpyxl=2.5.0b1=py36_0
- openssl=1.0.2n=0
- pandas=0.22.0=py36_0
- pillow=5.0.0=py36_0
- pip=9.0.1=py36_1
- plotly=2.2.3=py36_0
- pycodestyle=2.3.1=py36_0
- pydash=4.2.1=py_0
- pytest=3.3.2=py36_0
- pytest-cov=2.5.1=py36_0
- pytest-timeout=1.2.1=py_0
- pytest-xdist=1.22.0=py_0
- python=3.6.4=0
- pyyaml=3.12=py36_1
- regex=2017.12.12=py36_0
- requests=2.18.4=py36_1
- scipy=1.0.0=py36_blas_openblas_201
- setuptools=38.4.0=py36_0
- six=1.11.0=py36_1
- tensorboard=0.4.0rc3=py36_2
- ujson=1.35=py36_0
- urllib3=1.22=py36_0
- wheel=0.30.0=py36_2
- xlrd=1.1.0=py_2
- pytorch=0.3.0
- torchvision=0.2.0
- libgcc
- pip:
  - cloudpickle==0.5.2
  - colorlover==0.2.1
  - gym==0.9.4
  - gym[atari]
  - gym[box2d]
  - gym[classic_control]
  - opencv-python==3.4.0.12
  - psutil==5.4.3
  - pyopengl==3.1.0
  - ray==0.3.0
  - redis==2.10.6
  - tensorflow==1.5.0
  - theano==1.0.1
  - torch==0.3.0.post4
  - unityagents==0.2.0
